#!/bin/sh

# Automatic flashing of the sd card
# Default values: -image: custom-image
#                 -machine: imx8mm-lpddr4-evk
#                 -sd card path: /dev/mmcblk0
# Values can be changed by using arguments -m (--machine), -p (--path) and -i (--image)
# First arguments needs to be the path to the sd card that needs to be flashed

##################
# Default values #
##################
MACHINE="imx8mm-lpddr4-evk"
IMAGE="custom-image"
SDCARDPATH="/dev/mmcblk0"

#################
# HELP function #
#################
help() {
    echo "Script to automatically flash an sd card in a bitbake environment"
    echo "Only works if the bitbake init script is sourced and a '*.wic' or compressed form is generated by bitbake"
    echo
    echo "Syntax: flash_sd_card [-i {name}|-m {name}|-p {path}]"
    echo
    echo "Options:"
    echo "      -i  change the image name"
    echo "      -m  change the machine name"
    echo "      -p  change the sd card path"
    echo
    echo "Default values: "
    echo "      -image : custom-image"
    echo "      -machine : imx8mm-lpddr4-evk"
    echo "      -sd card path : /dev/mmcblk0"
    echo
}


######################
# Check input params #
######################
while true; do
    case "$1" in
        -m | --machine ) MACHINE="$2"; shift 2 ;;
        -i | --image ) IMAGE="$2"; shift 2 ;;
        -p | --path ) SDCARDPATH="$2"; shift 2 ;;
        -h | --help ) help; return 1 2>/dev/null; exit 1 ;;
        -- ) shift; break ;;
        * ) break ;;
    esac
done

#########################
# Check if image exists #
#########################
IMAGEPATH="$BUILDDIR/tmp/deploy/images/$MACHINE"
if [[ ! -f "$IMAGEPATH/$IMAGE-$MACHINE.wic.gz" && ! -f "$IMAGEPATH/$IMAGE-$MACHINE.wic" ]]; then
    echo -e "\033[0;31m| [ERROR] No image with the specified Machine and Image name found\033[0m"
    echo -e "\033[0;31m|\033[0m \t  Machine=$MACHINE"
    echo -e "\033[0;31m|\033[0m \t  Image=$IMAGE"
    echo -e "\033[0;31m|\033[0m \t  Seached for the image in the $BUILDDIR/tmp/deploy/images/$MACHINE/ directory"
    # To make it work if the script gets sourced
    return 1 2>/dev/null
    # When executing the script
    exit 1
fi

######################
# Check sd card path #
######################
if [[ ! -e "$SDCARDPATH" ]]; then
    echo -e "\033[0;31m| [ERROR] SD Card not found\033[0m"
    echo -e "\033[0;31m|\033[0m \t  SD Card path = $SDCARDPATH"

    return 1 2>/dev/null
    exit 1
fi

################################
# Check if wic image is zipped #
################################
if [[ -f "$IMAGEPATH/$IMAGE-$MACHINE.wic.gz" ]]; then
    echo "Image is compressed, decompressing..."
    gunzip -d -f "${IMAGEPATH}/${IMAGE}-${MACHINE}.wic.gz"
fi

#################################
# Flash the image to the sdcard #
#################################
if [[ -f "$IMAGEPATH/$IMAGE-$MACHINE.wic" ]]; then
    echo "Flashing the image to the sdcard..."
    sudo dd if="${IMAGEPATH}/${IMAGE}-${MACHINE}.wic" of="${SDCARDPATH}" bs=1M
else
    echo -e "\033[0;31m| [ERROR] No image with the specified Machine and Image name found\033[0m"
    echo -e "\033[0;31m|\033[0m \t  Seached for the image in the $BUILDDIR/tmp/deploy/images/$MACHINE/ directory"
    return 1 2>/dev/null
    exit 1
fi
